name: Update version if needed

on:
  schedule:
    - cron: "0 12 * * 1,3,5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-pulumi-repo-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout submodule to main
        run: |
          git checkout main
          git config --global user.name "Andreas Kvist"
          git config --global user.email "kvistcake@gmail.com"

        working-directory: output

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/pulumi-azure-native-cache

      - name: Check if @pulumi/azure-native has been updated
        continue-on-error: true
        run: |
          make check-version

      - name: Setup PNPM for submodule
        if: success()
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Build new version without cache and commit submodule
        run: |
          make output/update-and-commit

      # - name: Commit and push
      #   run: |
      #     pnpm install
      #     git config --global user.name "Andreas Kvist"
      #     git config --global user.email "kvistcake@gmail.com"
      #     git add -A
      #     git commit -m "Bumped version"
      #     git push
      #   working-directory: output
