name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

  build-and-test:
    runs-on: ubuntu-latest
    needs: [prepare-cache]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Build packages
        run: |
          make output
